package com.ws.wsAgenticSecurityGateway.audit.constants;

public enum AuditEventType {

    OAUTH2_AUTH_SUCCESS,
    OAUTH2_AUTH_FAILURE,
    OAUTH2_TOKEN_CLASSIFICATION_OVERRIDE,

    SERVER_SESSION_INITIALIZED,
    SERVER_SESSION_DISCONNECTED,
    SERVER_SESSION_IDLE_REAPED,
    SERVER_REQUEST_REJECTED,
    SERVER_TOOLS_LIST_REQUESTED,
    SERVER_RESOURCES_LIST_REQUESTED,
    SERVER_PROMPTS_LIST_REQUESTED,
    SERVER_TOOL_INVOCATION,
    SERVER_RESOURCE_READ,
    SERVER_NOTIFICATION_RECEIVED,

    CLIENT_SESSION_INITIALIZED,
    CLIENT_SESSION_DISCONNECTED,
    CLIENT_HEALTH_CHECK_FAILED,
    CLIENT_TOOLS_LIST_FETCHED,
    CLIENT_RESOURCES_LIST_FETCHED,
    CLIENT_PROMPTS_LIST_FETCHED,
    CLIENT_TOOL_INVOCATION,
    CLIENT_RESOURCE_READ,
    CLIENT_NOTIFICATION_RECEIVED,

    REGISTRY_CAPABILITY_REGISTERED,
    REGISTRY_CAPABILITY_UPDATED,
    REGISTRY_CAPABILITY_REMOVED,
    REGISTRY_BULK_LOAD,
    REGISTRY_SERVER_REFRESH,
    REGISTRY_NOTIFICATION_BROADCAST,

    ORCHESTRATION_TOOL_EXTRACTED,
    ORCHESTRATION_REGISTRY_LOOKUP,
    ORCHESTRATION_RESPONSE_RETURNED,
    ORCHESTRATION_ERROR,

    STS_TOKEN_MINTED,
    STS_KEY_ROTATED,
    STS_KEY_RETIRED,

    PDP_EVALUATION_REQUESTED,
    PDP_DECISION_RENDERED,

    PDP_POLICY_CREATED,
    PDP_POLICY_UPDATED,
    PDP_POLICY_DELETED,
    PDP_POLICY_TOGGLED,
    PDP_POLICY_VALIDATED,
    PDP_ENGINE_RELOADED,

    PDP_LLM_CHAT_REQUESTED,
    PDP_LLM_CHAT_COMPLETED,

    PDP_CUSTOM_ATTR_CREATED,
    PDP_CUSTOM_ATTR_UPDATED,
    PDP_CUSTOM_ATTR_DELETED,
    PDP_CUSTOM_ATTR_TOGGLED,

    SERVER_CONFIG_CREATED,
    SERVER_CONFIG_UPDATED,
    SERVER_CONFIG_DELETED,

    AGENT_APPROVED,
    AGENT_BLOCKED,
    AGENT_DEPROVISIONED,
    AGENT_CONNECTION_REJECTED,
    SESSION_IDENTITY_MISMATCH,

    HUMAN_USER_APPROVED,
    HUMAN_USER_BLOCKED,
    HUMAN_USER_UNBLOCKED,
    NHI_IDENTITY_APPROVED,
    NHI_IDENTITY_BLOCKED,
    NHI_IDENTITY_UNBLOCKED,
    HUMAN_CONNECTION_REJECTED,
    NHI_CONNECTION_REJECTED,
    AGENT_PENDING_REJECTED,
    BLOCKED_SESSION_TERMINATED,

    CAPABILITY_ACCESS_GRANTED,
    CAPABILITY_ACCESS_DENIED,
    CAPABILITY_PROFILE_CREATED,
    CAPABILITY_PROFILE_UPDATED,
    CAPABILITY_PROFILE_DELETED,
    CAPABILITY_PROFILE_ASSIGNED,
    CAPABILITY_PROFILE_UNASSIGNED,

    AUTH_CONFIG_CREATED,
    AUTH_CONFIG_UPDATED,
    AUTH_CONFIG_DELETED,
    AUTH_MODE_CHANGED,
    AUTH_CONFIG_VALIDATED,
    AUTH_CONFIG_VALIDATION_FAILED,
    AUTH_JWKS_REFRESHED,
    AUTH_GRACE_PERIOD_STARTED,
    AUTH_GRACE_PERIOD_ENDED,

    SYSTEM_STARTUP,
    SYSTEM_SHUTDOWN,
    SYSTEM_ERROR
}
