package com.ws.azureAdIntegration.constants;

import lombok.Getter;

@Getter
public enum PublishResourceType {
    VIRTUAL_MACHINE, DATABASE, STORAGE_ACCOUNT, ROLE_DEFINITION,
    NAMESPACE, CUSTOM_RESOURCE_DEFINITION, NODE, STORAGE_CLASS, PERSISTENT_VOLUME,
    DEPLOYMENT, SERVICE_ACCOUNT, SECRET, CONFIG_MAP, NETWORK_POLICY, JOB, CRON_JOB, INGRESS, SERVICE, REPLICA_SET, STATEFUL_SET, DAEMON_SET, CLUSTER_ROLE, NAMESPACE_ROLE;
}
