#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          azure:
#            client-id: 9acacaf6-02e1-4e06-84d9-5da4a7ffd2aa
#            client-secret: sJB8Q~G-YDCgTRPv6J~LZCQkNyDyUATwQvP_Bcx0
#            scope: openid, profile, email
#            redirect-uri: http://localhost:9495/login/oauth2/code/azure
#            authorization-grant-type: authorization_code
#        provider:
#          azure:
#            authorization-uri: https://login.microsoftonline.com/00b1d06b-e316-45af-a6d2-2734f62a5acd/oauth2/v2.0/authorize
#            token-uri: https://login.microsoftonline.com/00b1d06b-e316-45af-a6d2-2734f62a5acd/oauth2/v2.0/token
#            jwk-set-uri: https://login.microsoftonline.com/00b1d06b-e316-45af-a6d2-2734f62a5acd/discovery/v2.0/keys
#

#
#spring:
#  cloud:
#    azure:
#      active-directory:
#        enabled: true
#        profile:
#          tenant-id: 00b1d06b-e316-45af-a6d2-2734f62a5acd
#        credential:
#          client-id: 9acacaf6-02e1-4e06-84d9-5da4a7ffd2aa
#          client-secret: sJB8Q~G-YDCgTRPv6J~LZCQkNyDyUATwQvP_Bcx0
#        authorization-clients:
#          graph:
#            scopes: https://graph.microsoft.com/Analytics.Read, email



spring:
  cloud:
    azure:
      active-directory:
        client-id: "9acacaf6-02e1-4e06-84d9-5da4a7ffd2aa"
        client-secret: "sJB8Q~G-YDCgTRPv6J~LZCQkNyDyUATwQvP_Bcx0"
        tenant-id: "00b1d06b-e316-45af-a6d2-2734f62a5acd"
        redirect-uri: "http://localhost:9495/api/callback"
        authBaseUrl: "https://login.microsoftonline.com/"
        token-uri: "/oauth2/v2.0/token"
        graphBaseUrl: "https://graph.microsoft.com/v1.0"
        authorization-clients:
          azure:
            scopes: "openid,profile,email"

  datasource:
    url: "jdbc:postgresql://localhost:5432/ws-azureDb?currentSchema=azure_test"
    username: "postgres"
    password: "root"

  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: true

  logging:
    level:
      org:
        springframework:
          security: DEBUG

server:
  port: 9495