

spring:
  cloud:
    azure:
      active-directory:
        client-id: client_id
        client-secret: client_secret
        tenant-id: tenante_id
        authorization-clients:
          azure:
            scopes:
              - openid
              - profile
              - email




server:
  port: 9495
  forward-headers-strategy: native


  logging:
    level:
      org:
        springframework:
          security=DEBUG