package com.ws.azureKuberntesJIT.constant;

public enum K8ResourceType {
    NAMESPACE, NODE, DEPLOYMENT, SERVICE_ACCOUNT, SECRET, CONFIG_MAP, PERSISTENT_VOLUME, PERSISTENT_VOLUME_CLAIM,
    STORAGE_CLASS, CUSTOM_RESOURCE_DEFINITION, CLUSTER_ROLE, NAMESPACE_ROLE, NETWORK_POLICY;
}
