package com.ws.azureResourcesIntegration.constant;

public enum AzureResourcesType {
    SUBSCRIPTION, RESOURCE_GROUP, VM, STORAGE_ACCOUNT, SERVER, DATABASE, NETWORK_SECURITY_GROUP, VIRTUAL_NETWORK, MANAGEMENT_GROUP, UNKNOWN
}
