package com.ws.azureResourcesIntegration.constant;

public enum AzureResourcesType {
    SUBSCRIPTION, RESOURCE_GROUP, VIRTUAL_MACHINE, STORAGE_ACCOUNT, SERVER, DATABASE, NETWORK_SECURITY_GROUP, VIRTUAL_NETWORK, MANAGEMENT_GROUP, AZURE_KUBERNETES, NETWORK_INTERFACE, UNKNOWN

    }
