package com.ws.wsAgenticSecurityGateway.pdp.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Response DTO from the chatbot policy creation endpoint.
 * Contains the generated Cedar policy for admin review.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PolicyChatResponse {

    /** Whether the generation succeeded. */
    private boolean success;

    /** Generated Cedar policy text. */
    private String policyText;

    /** Suggested policy name (slug). */
    private String suggestedName;

    /** Human-readable description of what the policy does. */
    private String description;

    /** The effect: "permit" or "forbid". */
    private String effect;

    /** Explanation of the generated policy. */
    private String explanation;

    /** Error message if generation failed. */
    private String error;

    /** Whether this was generated by LLM or from a template. */
    private String source;

    public static PolicyChatResponse error(String message) {
        return PolicyChatResponse.builder()
                .success(false)
                .error(message)
                .build();
    }
}
