package com.ws.wsAgenticSecurityGateway.pdp.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Response DTO from the chatbot policy creation endpoint.
 *
 * <p>Contains either a generated Cedar policy for admin review,
 * a follow-up question from the LLM, or an error.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PolicyChatResponse {

    /** Whether the generation succeeded. */
    private boolean success;

    /** Generated Cedar policy text (null if follow-up question). */
    private String policyText;

    /** Suggested policy name (slug). */
    private String suggestedName;

    /** Human-readable description of what the policy does. */
    private String description;

    /** The effect: "PERMIT" or "FORBID". */
    private String effect;

    /** Explanation of the generated policy. */
    private String explanation;

    /** Error message if generation failed. */
    private String error;

    /** Whether this was generated by LLM or from a template. */
    private String source;

    /**
     * Whether the conversation is complete (policy generated)
     * or the LLM needs more information (follow-up question).
     */
    private boolean conversationComplete;

    /**
     * Follow-up question from the LLM when it needs more info.
     * Null when a policy has been generated.
     */
    private String followUpQuestion;

    /**
     * Validation result — null if valid, error message if Cedar syntax is invalid.
     * Only populated when a policy was generated (not for follow-up questions).
     */
    private String validationError;

    public static PolicyChatResponse error(String message) {
        return PolicyChatResponse.builder()
                .success(false)
                .error(message)
                .conversationComplete(true)
                .build();
    }
}
